import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ProductsProvider } from "./context/ProductProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthProvider } from "./context/AuthProvider";
import { CartProvider } from "./context/CartProvider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased flex flex-col min-h-screen`}
      >
        <ProductsProvider>
          <AuthProvider>
            <CartProvider>
              <Navbar></Navbar>
              <main className="flex-grow bg-zinc-50">
                {children}
              </main>
              <Footer />
            </CartProvider>
          </AuthProvider>
        </ProductsProvider>
      </body>
    </html>
  );
}
